# Generated by Django 4.2.1 on 2023-05-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('resID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unsure')], max_length=1)),
                ('civilStatus', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('Se', 'Separated'), ('W', 'Widowed')], max_length=2)),
                ('sitio', models.CharField(choices=[('I', 'Ilaya'), ('G', 'Green Heights'), ('W', 'White House'), ('D', 'Don Elpidio'), ('S', 'Sambat'), ('P', 'Pinagpala'), ('C', 'Centro')], max_length=1)),
            ],
        ),
    ]
